
# This is absolutely not finished and just copied from different sources
notifications:
email: false

language: python
python:
#  - "2.6"
#  - "2.7"
#  - "3.2"
#  - "3.3"
#  - "3.4"
  - "3.5"
#  - "3.5-dev" # 3.5 development branch
#  - "3.6"
#  - "3.6-dev" # 3.6 development branch
#  - "3.7-dev" # 3.7 development branch
#  - "nightly" # currently points to 3.7-dev

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip3 install --upgrade git+https://github.com/fmaussion/salem.git
  - pip3 install --upgrade git+https://github.com/OGGM/oggm.git
  - cd /root/crampon
  - pip install -e .
  - py.test ./crampon --cov=crampon --cov-report term-missing

# command to run tests
script: py.test  # or py.test for Python versions 3.5 and below
