# This is almost a copy from salem, except that python 2.7 is not supported
language: python
sudo: required
notifications:
  email: false

branches:
  except:
    - docs

matrix:
  fast_finish: true
  include:
  - python: 3.6
    env: CONDA_ENV=py36-all MPL=--mpl
  - python: 3.6
    env: CONDA_ENV=py36-xarray-dev MPL=--mpl
  - python: 3.6
    env: CONDA_ENV=py36-oggm-dev MPL=--mpl
  - python: 3.6
    env: CONDA_ENV=py36-all-rc MPL=--mpl
  allow_failures:
  - python: 3.6
    env: CONDA_ENV=py36-xarray-dev MPL=--mpl
  - python: 3.6
    env: CONDA_ENV=py36-oggm-dev MPL=--mpl
  - python: 3.6
    env: CONDA_ENV=py36-all-rc MPL=--mpl

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - pip install pyyaml

install:
  - conda env create --file ci/requirements-$CONDA_ENV.yml --quiet
  - source activate test_env
  - pip install -e .

script:
  - pytest crampon $MPL --cov=crampon --cov-report term-missing;

after_success:
- coveralls
